### ISSUE TITLE
VideoPatcher crashes on attempt to open file during process

### ISSUE THREAD

**Issue by Sergey-patcher** [da8eat/VideoEditorInstaller#1]
str:      
1) Run AMCDXVideoPatcher  
2) Open any Prores MOV file
3) Set in and out points
4) Start any process (eg Insert from PNG or Save to PNG)
5) Open another file during process    
                                                  
expected result:  file opens                    
current result:  crash

**Comment by da8eat** [comment]
fixed in 0.1.0
