### ISSUE TITLE
Blur works incorrectly if set some left / right value

### ISSUE THREAD

**Issue by Sergey-patcher** [da8eat/VideoEditorInstaller#4]
str:
    1. Run AMCDXVideoPatcher
    2. Open any Prores MOV file
    3. Set Value for left / right (eg 120 / 176)
    4. Click "Blur" button  
    5. See result of blur 

expected result: blur was done correctly (selected place of frame was blurred)
current result: green line appears on frame after blur

**Comment by Sergey-patcher** [comment]
![Blur](https://user-images.githubusercontent.com/61028740/74488302-6ef2fd00-4eca-11ea-8e13-87c789ef8a13.png)

**Comment by da8eat** [comment]
will not fix: blur will be disabled in future versions
