### ISSUE TITLE
VideoPatcher crashes on attempt to open Prores CC file in Edit Metadta tab

### ISSUE THREAD

**Issue by Sergey-patcher** [da8eat/VideoEditorInstaller#6]
str:
    1. Run AMCDXVideoPatcher
    2. Go to Edit Metadta tab
    3. Open any Prores MOV file with closed captions

expected result: file opens
current result: crash

**Comment by da8eat** [comment]
what is Prores CC?

**Comment by Sergey-patcher** [comment]
Prores file with closed captions (1080i 50.94, 1080p 23.98 I tried to open)

пн, 30 мар. 2020 г., 09:25 Alex Mogurenko <notifications@github.com>:
