### ISSUE TITLE
App should not allow to open no MOV files in Edit Metadta tab

### ISSUE THREAD

**Issue by Sergey-patcher** [da8eat/VideoEditorInstaller#8]
str:
1. Run AMCDXVideoPatcher
2. Go to Edit Metadta tab
3. Open any no Prores file (eg DNxHD)

expected result: app shows error message "Failed to open file"
current result: file opens (as expeсted meatdata such file are not displayed)

**Comment by da8eat** [comment]
Metadata editor allows to edit all mov files not only prores files

**Comment by Sergey-patcher** [comment]
Clear. Mxf files also can be opened there.

пн, 30 мар. 2020 г., 09:27 Alex Mogurenko <notifications@github.com>:
